[metadata]
	name = 'Bravely Default Text'
	variable_size_fields = [['','null','','Filename']]
	multiply_fields = [['','']] 

[[fields]] 
	name = 'Next Entry Offset'
	size = 4
	data_type = 'Offset'
	display_format = 'hexle'
	description = 'Offset to next entry index.fs'

[[fields]]
	name = 'File Start Offset'
	size = 4
	data_type = 'Offset'
	display_format = 'hexle'
	description = 'Start offset of file in crowd.fs'

[[fields]]
	name = 'File Length'
	size = 4
	data_type = 'Length'
	display_format = 'hexle'
	description = 'Length of file in crowd.fs'

[[fields]]
	name = 'Unknown Data'
	size = 4
	data_type = 'N/A'
	display_format = 'hex'
	description = 'N/A'

[[fields]]
	name = 'Filename'
	size = 0
	data_type = 'ASCII'
	display_format = 'ascii'
	description = 'Name of file in crowd.fs'

