[metadata]
    name = 'GBA-Cartridge-Header'
    variable_size_fields = [['','','','']]
	multiply_fields = [['','']] 

[[fields]]
    name = "ROM Entry Point"
    size = 4
    data_type = "ARM instruction"
    display_format = 'hex'
    description = '32bit ARM branch opcode, eg. B rom_start'

[[fields]]
    name = "Nintendo Logo"
    size = 156
    data_type = "Compressed bitmap"
    display_format = 'hex'
    description = 'Compressed Nintendo logo bitmap'

[[fields]]
    name = "Game Title"
    size = 12
    data_type = "ASCII"
    display_format = 'ascii'
    description = 'Uppercase ascii, max 12 characters'

[[fields]]
    name = "Game Code"
    size = 4
    data_type = "ASCII"
    display_format = 'ascii'
    description = 'Uppercase ascii, 4 characters'

[[fields]]
    name = "Maker Code"
    size = 2
    data_type = "ASCII"
    display_format = 'ascii'
    description = 'Uppercase ascii, 2 characters'

[[fields]]
    name = "Fixed Value"
    size = 1
    data_type = "N/A"
    display_format = 'hex'
    description = 'Must be 96h, required!'

[[fields]]
    name = "Main Unit Code"
    size = 1
    data_type = "N/A"
    display_format = 'hex'
    description = '00h for current GBA models'

[[fields]]
    name = "Device Type"
    size = 1
    data_type = "N/A"
    display_format = 'hex'
    description = 'usually 00h) (bit7=DACS/debug related'

[[fields]]
    name = "Reserved Area"
    size = 7
    data_type = "N/A"
    display_format = 'hex'
    description = 'Should be zero filled'

[[fields]]
    name = "Software Version"
    size = 1
    data_type = "N/A"
    display_format = 'hex'
    description = 'Usually 00h'

[[fields]]
    name = "Complement Check"
    size = 1
    data_type = "Checksum"
    display_format = 'hex'
    description = 'Header checksum, required!'

[[fields]]
    name = "Reserved Area"
    size = 2
    data_type = "N/A"
    display_format = 'hex'
    description = 'Should be zero filled'



