[metadata]
name = 'FAT16-bootsector'
size = 512

[[fields]]
    name = "Start jump"
    size = 0x03
    data_type = "x86_32"
    display_format = 'x86_32'
    description = 'Code to jump to the bootstrap code'

[[fields]]
    name = "OEM ID"
    size = 0x08
    data_type = "ascii"
    display_format = 'ascii'
    description = 'OEM ID - Name of the formatting OS'

[[fields]]
    name = "Sector Size"
    size = 0x02
    data_type = "sizele"
    display_format = 'hexle'
    description = 'How large in bytes each sector is'

[[fields]]
    name = "Sectors Per Cluster"
    size = 0x01
    data_type = "count"
    display_format = 'hex'
    description = 'Number of sectors per cluster'

[[fields]]
    name = "Number Of Reserved Sectors"
    size = 0x02
    data_type = "countle"
    display_format = 'hexle'
    description = 'Number of reserved sectors'

[[fields]]
    name = "Number Of FAT Copies"
    size = 0x01
    data_type = "count"
    display_format = 'hex'
    description = 'Number of FAT copies in filesystem'

[[fields]]
    name = "Root Entry Count"
    size = 0x02
    data_type = "countle"
    display_format = 'hexle'
    description = 'Number of possible entries in root directory'

[[fields]]
    name = "Small Number of Sectors"
    size = 0x02
    data_type = "count"
    display_format = 'hex'
    description = 'Total number of sectors in the volume'

[[fields]]
    name = "Media Descriptor"
    size = 0x01
    data_type = "N/A"
    display_format = 'hex'
    description = 'Indicates capactiy and physical format'

[[fields]]
    name = "Sectors Per FAT"
    size = 0x02
    data_type = "countle"
    display_format = 'hexle'
    description = 'Number of sectors per FAT'

[[fields]]
    name = "Sectors per Track"
    size = 0x02
    data_type = "countle"
    display_format = 'hexle'
    description = 'Number of sectors per track'

[[fields]]
    name = "Number of Heads"
    
    size = 0x02
    data_type = "countle"
    display_format = 'hexle'
    description = 'Head value when volume was formatted'

[[fields]]
    name = "Hidden Sectors"
    size = 0x04
    data_type = "countle"
    display_format = 'hexle'
    description = 'Number of sectors preceding first sector of volume'

[[fields]]
    name = "Large Number of Sectors"
    
    size = 0x04
    data_type = "sizele"
    display_format = 'hexle'
    description = 'Total number of sectors in volume (32MB +)'

[[fields]]
    name = "Drive Number"
    size = 0x01
    data_type = "N/A"
    display_format = 'hex'
    description = 'Int 13h drive number'

[[fields]]
    name = "Reserved"
    size = 0x01
    data_type = "N/A"
    display_format = 'hex'
    description = 'Reserved byte'

[[fields]]
    name = "Extended Boot Signature"
    size = 0x01
    data_type = "N/A"
    display_format = 'hex'
    description = 'Reserved byte'

[[fields]]
    name = "Volume Serial Number"
    size = 0x04
    data_type = "N/A"
    display_format = 'hexle'
    description = 'Volume serial number'

[[fields]]
    name = "Volume Label"
    size = 0x0B
    data_type = "ascii"
    display_format = 'ascii'
    description = 'Volume label'

[[fields]]
    name = "File System Type"
    size = 0x08
    data_type = "ascii"
    display_format = 'ascii'
    description = 'Info display only'

[[fields]]
    name = "Bootstrap Code"
    size = 0x1C0
    data_type = "x86_32"
    display_format = 'x86_32'
    description = 'OS bootstrap code'

[[fields]]
    name = "Boot Sector Signature"
    size = 0x02
    data_type = "signature"
    display_format = 'hexle'
    description = 'Boot sector signature'