[metadata]
name = 'test'
fixed_size = true
size = 0x48
big_endian = false

[[fields]]
    name = "Hex"
    size = 0x10
    data_type = "raw"
    display_format = 'hex'
    description = 'Display hex formatting'

[[fields]]
    name = "ascii"
    size = 0x10
    data_type = "ascii"
    display_format = 'ascii'
    description = 'Display ascii formatting'

[[fields]]
    name = "Loopback be"
    size = 0x04
    data_type = "ipv4be"
    display_format = 'ipv4be'
    description = 'Display big endian IPv4'

[[fields]]
    name = "Loopback le"
    size = 0x04
    data_type = "ipv4le"
    display_format = 'ipv4le'
    description = 'Display little endian IPv4 '

[[fields]]
    name = "utf16 be"
    size = 0x10
    data_type = "utf16be"
    display_format = 'utf16be'
    description = 'Display big endian utf16'

[[fields]]
    name = "utf16 le"
    size = 0x10
    data_type = "utf16le"
    display_format = 'utf16le'
    description = 'Display little endian utf16'

[[fields]]
    name = "x86_32"
    size = 0x03
    data_type = "x86_32"
    display_format = 'x86_32'
    description = 'Code to jump to the bootstrap code'





